Remove scan_width of cfg80211.h; deleted since 6.7
cfg80211_scan_request struct no longer has the scan_width member:
https://github.com/torvalds/linux/commit/5add321c329b1746589b51359259666ca3dbe219

Remove reliance on it from wlan/os/linux/gl_cfg80211.c in MT6632/MT7668
driver to set channel width for scanning. Uses default NL80211_CHAN_WIDTH_20_NOHT

Should-fix:
[error]drivers/net/wireless/mediatek/mt76x8/drv_wlan/MT6632/wlan/os/linux/gl_cfg80211.c:867:74: error: 'struct cfg80211_scan_request' has no member named 'scan_width'

Signed-off-by: feeRnt <81442162+feeRnt@users.noreply.github.com>