Add Kconfig changes, and select patches for compiling up to kernel version 5.4 from ChalesYu/mt7668sn:
1. 9becbc888d5a51d11f92a2fe3297f1f0ad6f2367
    don't want some warnings be treat as error

2. fd13e9aab2bcd725f80298d2d662b5d8ecb45759
    Fix build with kernel 4.11

3. 531b86beac89a0aea9fdae8ba96159bd9f9fee51
    Fix build with kernel 4.12

4. eeaa296c95438f5b8a82ceabeccd1d84f2fcb0f0
    don't know how to fix error
    error: ‘struct net_device’ has no member named ‘last_rx’
 -- [Maybe we should fix this?]

5. f8a61313959b7986a3a44b169dd5670cd8530202
  [error]Fix cfg80211_schd_scan error and memory error
  error: call to ‘__read_overflow2’ declared with attribute error:
 -- [This maybe causes pin control deficiency...]

6. bbbb382b83422b17b0deabec69ca9ce717cbfbcd
    Other fix for kernel 4.12

7. 7ff095ed4cdd53e4cec9ce2d78429a11ba0f6935
    Add support for kernel 4.14

8. d08146c2a5db6056781de53d99814ade725f39d6
    [Fix error] destructor -> priv_destructor

9. 42b10f91e8f3b16b8ce9af965e8c7f9af5237a11
    Fix build with kernel 4.15

10. a6b7f0a718ad74072ca8d2d60cf936c470b4b4a8
    Update for kernel 4.19

11. 7ad6908ac3a3ae83484912cb0aeba52ee424add7
    Update for kernel 4.20

12. 546cf0ae5fe53cc1c07527dea1ea1cb497572264
    Fix build in kernel 5.1

13. a61ebb1cf17d1fcd23a5d4bad23831d76f9cf121
    kernel 5.0: Remove 'type' argument from access_ok() function

14. c7f43a84fab4af2888ca1728c22f2462db9f2f97
    fix aarch64 compilation error

15. 364bed09429bd27bc24b57640320cd297f6269ab
    kernel 5.0 : Remove wakelock.h dependencies

    Convet the drivers to use the wakeup sources in Linux PM API to acieve
    the very same goal.

16. 0e99cd94b1ff031993d610ace3f11c39bd849848
    [Fix error] memory issue at nic_cmd_event.c

17. 8fffee64fc3e8ce258513e92f3f5931774a1f3ba
    [Fix error] memory issue at gl_hook_api.c

18. 54aa5c691d6763fcd51c56faacf635b925ce1e8c
    Disable P2P mode

    P2P mode looks have some bug, and make wifi connect unstable.
  -- [IMPORTANT]

19. 13d85daf58bb7f4ac9e5f2e83fc43aa15a37b1bd *
    Fix builds with kernel 5.2

20. ec133517b8452ae492455b964cd6e13c31181a63
    Fix "fall through" warnings

21. db9a1d7050a01ae584eb49d5e595007a1a2cfc95
    Fix "-Wmemset-elt-size" Warnings
22. b3f9fa994c78b0e870d00c4cf52b5e280a062066
    fix for 5.3
    Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

23. f73d27bdcb45711a74a52fbc7a5c5ca29e59684d
    update .gitignore

24. 1521bc3638f0f3c24f3d4addc88efb16d2b37ed9
    rework for kernel 4.20 (get_monotonic_boottime)

25. [DROPPED]
64c13131379bc8edbe6829f2af486dbd8f99e490
    enable support CFG_DRIVER_INF_NAME_CHANGE
  -- [Since I thought we are not usually loading as a module
  Maybe turn on in the future]

26. e5751064a5c5b6fca076f465b8ddc333efbcc867
    Maintain kernel 5.6 compatibility

27. [DROPPED]
38050a64087a8c3346bc08d7786b48b746126ab8
    clean logs in AP mode
  -- [Logs are always good]

28. [DROPPED]
4430c42063f1e01380ee64aa6e3dc24979ede97b
    Fix build for kernel 5.7

    set TK_MET_PROFILING_SUPPORT = no
    because kallsyms_on_each_symbol is unexport in 5.7
  -- [Re-enable for 5.15...]

29. f299357d7dee6d773c30a7a80627eb4d2d01b272
    mt7668s: Fix build for kernel 5.8

30. 46e55e77202ffd015cd8f72cb3c8df3f85d86e7e
    Allow clean in Makefile

31. d48ef973f9bba7ce2ac60c2bca8bc27bed6f271b
    Use KSRC instead KERNELDIR for test

32. [DROPPED]
e6d099c9cf2c2cdb882364d97095307ccd2935b6
    Fix build for kernel 5.9

33. [DROPPED]
d6be81de2b4c9e998ea8d977edcaa460679670ab
    Fix build for kernel 5.10

-- Removed extra files:
  ated, wifitest, elvis, etc.

Mainly authored by: 574249312 (at) qq (dot) com
Commited by       : 81442162+feeRnt@users.noreply.github.com