Update link_sta_params of params, for Linux >= 6.0
Many elements of include/net/cfg80211.h's station_parameters
were deleted, being replaced by their existent equivalents in
link_station_parameters.

Update the pointers in wlan/os/linux/gl_cfg80211.c to reflect
all of these changes.

Should Fix:
[error]drivers/net/wireless/mediatek/mt76x8/drv_wlan/MT6632/wlan/os/linux/gl_cfg80211.c:2723:26: error: 'struct station_parameters' has no member named 'supported_rates'; did you mean 'supported_channels'?

[error]drivers/net/wireless/mediatek/mt76x8/drv_wlan/MT6632/wlan/os/linux/gl_cfg80211.c:2757:21: error: 'struct station_parameters' has no member named 'ht_capa'; did you mean 'ext_capab'?

[error]drivers/net/wireless/mediatek/mt76x8/drv_wlan/MT6632/wlan/os/linux/gl_cfg80211.c:2773:21: error: 'struct station_parameters' has no member named 'vht_capa'; did you mean 'ext_capab'?
etc.

Signed-off-by: feeRnt <81442162+feeRnt@users.noreply.github.com>