Update ref: del_timer_sync (now timer_delete_sync)
Changes reflecting update from Kernel 6.15:
https://github.com/torvalds/linux/commit/8fa7292fee5c5240402371ea89ab285ec856c916

Should fix:

[error]drivers/net/wireless/mediatek/mt76x8/drv_wlan/MT6632/wlan/os/linux/gl_init.c:2781:25: error: implicit declaration of function 'del_timer_sync'; did you mean 'dev_mc_sync'? [-Werror=implicit-function-declaration]

[error]drivers/net/wireless/mediatek/mt76x8/drv_wlan/MT6632/wlan/os/linux/gl_kal.c:3542:17: error: implicit declaration of function 'del_timer_sync'; did you mean 'dev_mc_sync'? [-Werror=implicit-function-declaration]

Credits: https://github.com/asterisk/dahdi-linux/pull/92/changes/520cf14256503b4fb5449d72e3c179065d17871a

Signed-off-by: feeRnt <81442162+feeRnt@users.noreply.github.com>