build: Fix thinLTO build cache template bug
Error: The template is not valid.
.github/workflows/build-kernel_latest_clang_thinLTO.yaml
(Line: 77, Col: 16): hashFiles('**/Dockerfile') failed. Fail to
hash files under directory '/home/runner/work/ps4-linux-12xx/ps4-linux-12xx'

The bug has no cause, no reason.
Updating to cache@v4 may help, but for now
test renaming and "replacing" the workflow in question.
Maybe it will "refresh" some internal cache thing.

This is the commit that broke my build, but only for thinLTO:
https://github.com/feeRnt/ps4-linux-12xx/commit/aaeb744cd9a98e8513ba3e6bec029f122e75cade

See also:
https://github.com/actions/runner-images/issues/13341
https://github.com/actions/runner/issues/449
---

Make only thinLTO build run on push to test.